config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :proyects
  root to: 'proyects#index'
  get 'pages/index'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proyect.rb
class Proyect < ApplicationRecord
  has_and_belongs_to_many :personas
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: [:show, :edit, :update, :destroy]

  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
    @user = User.all
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
    @proyect.personas << personas
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: 'Proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:name)
    end
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/proyects/_form.html.erb
<%= form_with(model: proyect, local: true) do |form| %>
  <% if proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyect.errors.count, "error") %> prohibited this proyect from being saved:</h2>

      <ul>
      <% proyect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<h1>Editing Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Show', @proyect %> |
<%= link_to 'Back', proyects_path %>

app/views/proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Trabajador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= proyect.name %></td>
        <td><%= proyect.personas.pluck(:name).join(", ") %></td>
        <td><%= link_to 'Show', proyect %></td>
        <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
        <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyect', new_proyect_path %>

app/views/proyects/new.html.erb
<h1>New Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Back', proyects_path %>

app/views/proyects/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyecto: <%= @proyect.name %></h1>


<%= link_to 'Edit', edit_proyect_path(@proyect) %> |
<%= link_to 'Back', proyects_path %>